import type { Metadata } from 'next';
import { Nunito, Poppins, Roboto } from 'next/font/google';
import { Container } from '@/components/layout/Container';
import './globals.css';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});
const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'NovaTech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <Container>
      <html lang="en">
        <body className={`${nunito.variable} ${poppins.variable} ${roboto.variable}  antialiased`}>{children}</body>
      </html>
    </Container>
  );
}
