import type { Metadata } from 'next';
import { Roboto, Poppins, Nunito } from 'next/font/google';
import Container from '@/components/common/Container';
import Navbar from '@/components/layout/Header/Header';
import './globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.variable} ${poppins.variable} ${nunito.variable} antialiased`}>
        <Container>
          <Navbar />
          {children}
        </Container>
      </body>
    </html>
  );
}
